### ISSUE TITLE
Connect database on the server

### ISSUE THREAD

**Issue by mhkhan4** [e-commerce-cse-442/Books2Go#31]
**Task Tests **

*Test 1*
1) Run heroku local.
2) Print the process.env.DATABASE_URL using console.log.
3) Ensure that in the console that the correct database url prints according to heroku configs.
4) Ensure that in the console that the correct database url prints same as heroku configs on local .env file.

**Comment by karlisat** [comment]
Ok, I see the steps taken. Remember to document the steps taken.
