### ISSUE TITLE
write all the alert messages inside the popup page.

### ISSUE THREAD

**Issue by HasanulRafi** [e-commerce-cse-442/Books2Go#57]

**Comment by HasanulRafi** [comment]
Wrote basic code for the page to connect

**Comment by karlisat** [comment]
Done.

**Comment by Vlad-Bosovets** [comment]
** Tasks Tests: **

Test 1

Go to the register page on Books2Go.
Register an account with a password only 3 letters long. 
There should be an error that the password is too small.
The account should not be in the database.

Test 2

Go to the login page.
Login with a correct username but incorrect password.
There should be an error and the user should not be logged in.
