### ISSUE TITLE
Create a cart. Should have the functionality of displaying the books added by the logged in user along with their product details.

### ISSUE THREAD

**Issue by mhkhan4** [e-commerce-cse-442/Books2Go#69]
**Task Tests:**

*Test 1*
1. Go to the website books2go.herokoapp.com
2. Click on the logo.
3. Choose a product and click on "add to cart".
4. Click on the cart button
5. The book should be visible there.

*Test 2*

**Comment by karlisat** [comment]
Done in time.

**Comment by karlisat** [comment]
I understand that this is completed.
